#uruchamianie konsoli w przeglądarce -> http://localhost:8080/h2-console

my-configuration-properties:
  app-name: Peter Kowalski
  app-description: Kowal to menelanto
  app-date-birth: 13-12-1987

static-value: SEX

spring:
  profiles.active: test
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456asd
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    validationQuery: SELECT 1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop